spring:
  profiles:
    include: jwt

  datasource:
    url: jdbc:mysql://swithdb.cpzwdohpwrma.ap-northeast-2.rds.amazonaws.com:3306/swith?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: aivle
    password: aivle202303
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

file:
  dir: /Users/hwanjun/Library/CloudStorage/OneDrive-uos.ac.kr/Workspace/files/