spring:
  profiles:
    include: jwt
#
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/swith;MODE=MYSQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:mysql://swithdb.cpzwdohpwrma.ap-northeast-2.rds.amazonaws.com:3306/swith?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: aivle
    password: aivle202303
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

file:
  dir: /Users/hwanjun/Library/CloudStorage/OneDrive-uos.ac.kr/Workspace/files/

cloud:
  aws:
    s3:
      bucket: a031293-bucket
    credentials:
      access-key: AKIAVDZ23WGFXT7BPHSC
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
