spring:
  profiles:
    include: jwt

  datasource:
    url: jdbc:h2:tcp://localhost/~/swith;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

file:
  dir: /Users/hwanjun/Library/CloudStorage/OneDrive-uos.ac.kr/Workspace/files/

cloud:
  aws:
    s3:
      bucket: a031293-bucket
    credentials:
      access-key: AKIAVDZ23WGFXT7BPHSC
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
